/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: patrix (https://sketchfab.com/patrix)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/mayan-temple-5a62592e2c9d41be96ea888472779544
Title: Mayan Temple
*/

import React, {useEffect} from 'react';
import {CameraControls, useGLTF} from '@react-three/drei';

export function Maya(props) {
  const {nodes, materials} = useGLTF('/models/mayan_temple.glb');
  const groupRef = React.useRef();
  const cameraControlsRef = React.useRef();


  useEffect(() => {
    if (groupRef.current) {
      cameraControlsRef.current.distance = 20;
      cameraControlsRef.current.elevate(5, false)


    }
  }, []);


  return (
    <>
      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={5}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_2.geometry}
            material={materials.base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials.base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.transparent}
          />
        </group>
      </group>
      <CameraControls ref={cameraControlsRef}/>
    </>


  );
}

useGLTF.preload('/models/mayan_temple.glb');
